/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;

import java.awt.Color;

/**
 *
 * @author sanilso
 */
public class Hist_1 extends javax.swing.JFrame {

    /**
     * Creates new form Hist_1
     */
    public Hist_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        TxtBan1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtBan3 = new javax.swing.JTextField();
        TxtBan4 = new javax.swing.JTextField();
        TxtBan5 = new javax.swing.JTextField();
        TxtBan6 = new javax.swing.JTextField();
        TxtBan7 = new javax.swing.JTextField();
        TxtBan8 = new javax.swing.JTextField();
        TxtBan9 = new javax.swing.JTextField();
        TxtBan10 = new javax.swing.JTextField();
        TxtBan11 = new javax.swing.JTextField();
        TxtBan12 = new javax.swing.JTextField();
        TxtBan13 = new javax.swing.JTextField();
        txtSuz1 = new javax.swing.JTextField();
        txtSuz2 = new javax.swing.JTextField();
        txtSuz3 = new javax.swing.JTextField();
        txtSuz4 = new javax.swing.JTextField();
        txtSuz5 = new javax.swing.JTextField();
        txtSuz6 = new javax.swing.JTextField();
        txtSuz = new javax.swing.JTextField();
        txtSuz7 = new javax.swing.JTextField();
        txtSuz8 = new javax.swing.JTextField();
        txtSuz9 = new javax.swing.JTextField();
        txtbr1 = new javax.swing.JTextField();
        txtbr4 = new javax.swing.JTextField();
        txtbr2 = new javax.swing.JTextField();
        txtbr3 = new javax.swing.JTextField();
        txtbr5 = new javax.swing.JTextField();
        txtBor = new javax.swing.JTextField();
        txtBor1 = new javax.swing.JTextField();
        txtBor2 = new javax.swing.JTextField();
        txtBor3 = new javax.swing.JTextField();
        txtBor4 = new javax.swing.JTextField();
        txtBor5 = new javax.swing.JTextField();
        txtBor6 = new javax.swing.JTextField();
        txtBor7 = new javax.swing.JTextField();
        txtBor8 = new javax.swing.JTextField();
        txtFer = new javax.swing.JTextField();
        txtFer1 = new javax.swing.JTextField();
        txtFer2 = new javax.swing.JTextField();
        txtFer3 = new javax.swing.JTextField();
        txtFer4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TxtBan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan1KeyReleased(evt);
            }
        });

        jLabel1.setText("Bandeirantes");

        jLabel2.setText("Suzana Dias");

        jLabel3.setText("Fernão");

        jLabel4.setText("Borba Gato");

        jLabel5.setText("Brasil");

        TxtBan3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan3KeyReleased(evt);
            }
        });

        TxtBan4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan4KeyReleased(evt);
            }
        });

        TxtBan5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan5KeyReleased(evt);
            }
        });

        TxtBan6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan6KeyReleased(evt);
            }
        });

        TxtBan7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan7KeyReleased(evt);
            }
        });

        TxtBan8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan8KeyReleased(evt);
            }
        });

        TxtBan9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan9KeyReleased(evt);
            }
        });

        TxtBan10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan10KeyReleased(evt);
            }
        });

        TxtBan11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan11KeyReleased(evt);
            }
        });

        TxtBan12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan12KeyReleased(evt);
            }
        });

        TxtBan13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBan13KeyReleased(evt);
            }
        });

        txtSuz1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz1KeyReleased(evt);
            }
        });

        txtSuz2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz2KeyReleased(evt);
            }
        });

        txtSuz3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz3KeyReleased(evt);
            }
        });

        txtSuz4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz4KeyReleased(evt);
            }
        });

        txtSuz5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz5KeyReleased(evt);
            }
        });

        txtSuz6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz6KeyReleased(evt);
            }
        });

        txtSuz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuzKeyReleased(evt);
            }
        });

        txtSuz7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz7KeyReleased(evt);
            }
        });

        txtSuz8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz8KeyReleased(evt);
            }
        });

        txtSuz9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuz9KeyReleased(evt);
            }
        });

        txtbr1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbr1KeyReleased(evt);
            }
        });

        txtbr4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbr4KeyReleased(evt);
            }
        });

        txtbr2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbr2KeyReleased(evt);
            }
        });

        txtbr3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbr3KeyReleased(evt);
            }
        });

        txtbr5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbr5KeyReleased(evt);
            }
        });

        txtBor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBorKeyReleased(evt);
            }
        });

        txtBor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor1KeyReleased(evt);
            }
        });

        txtBor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor2KeyReleased(evt);
            }
        });

        txtBor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor3KeyReleased(evt);
            }
        });

        txtBor4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor4KeyReleased(evt);
            }
        });

        txtBor5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor5KeyReleased(evt);
            }
        });

        txtBor6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor6KeyReleased(evt);
            }
        });

        txtBor7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor7KeyReleased(evt);
            }
        });

        txtBor8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBor8KeyReleased(evt);
            }
        });

        txtFer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFerKeyReleased(evt);
            }
        });

        txtFer1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFer1KeyReleased(evt);
            }
        });

        txtFer2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFer2KeyReleased(evt);
            }
        });

        txtFer3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFer3KeyReleased(evt);
            }
        });

        txtFer4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFer4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtSuz1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtSuz4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuz7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbr2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbr3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbr4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbr5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtBor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFer3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFer4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBor8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(TxtBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtSuz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtSuz7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtSuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txtbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtbr2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtbr3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtbr4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtbr5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(txtBor7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtFer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFer3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFer4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBor8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan1KeyReleased
        if(TxtBan1.getText().equals("B") || TxtBan1.getText().equals("b")){
                TxtBan1.setBackground(Color.green);
                TxtBan13.requestFocus();
            }
        else if (TxtBan1.getText().equals("")){
            TxtBan1.setBackground(Color.white);
        }
            else{
                TxtBan1.setBackground(Color.red);
                TxtBan1.selectAll();
            }
    }//GEN-LAST:event_TxtBan1KeyReleased

    private void TxtBan13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan13KeyReleased
        if(TxtBan13.getText().equals("A") || TxtBan13.getText().equals("a")){
                TxtBan13.setBackground(Color.green);
                TxtBan3.requestFocus();
            }
        else if (TxtBan13.getText().equals("")){
            TxtBan13.setBackground(Color.white);
        }
            else{
                TxtBan13.setBackground(Color.red);
                TxtBan13.selectAll();
            }
    }//GEN-LAST:event_TxtBan13KeyReleased

    private void TxtBan3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan3KeyReleased
        if(TxtBan3.getText().equals("N") || TxtBan3.getText().equals("n")){
                TxtBan3.setBackground(Color.green);
                TxtBan4.requestFocus();
            }
        else if (TxtBan3.getText().equals("")){
            TxtBan3.setBackground(Color.white);
        }
            else{
                TxtBan3.setBackground(Color.red);
                TxtBan3.selectAll();
            }
    }//GEN-LAST:event_TxtBan3KeyReleased

    private void TxtBan4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan4KeyReleased
        if(TxtBan4.getText().equals("D") || TxtBan4.getText().equals("d")){
                TxtBan4.setBackground(Color.green);
                TxtBan5.requestFocus();
            }
        else if (TxtBan4.getText().equals("")){
            TxtBan4.setBackground(Color.white);
        }
            else{
                TxtBan4.setBackground(Color.red);
                TxtBan4.selectAll();
            }
    }//GEN-LAST:event_TxtBan4KeyReleased

    private void TxtBan5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan5KeyReleased
        if(TxtBan5.getText().equals("E") || TxtBan5.getText().equals("e")){
                TxtBan5.setBackground(Color.green);
                TxtBan6.requestFocus();
            }
        else if (TxtBan5.getText().equals("")){
            TxtBan5.setBackground(Color.white);
        }
            else{
                TxtBan5.setBackground(Color.red);
                TxtBan5.selectAll();
            }
    }//GEN-LAST:event_TxtBan5KeyReleased

    private void TxtBan6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan6KeyReleased
        if(TxtBan6.getText().equals("I") || TxtBan6.getText().equals("i")){
                TxtBan6.setBackground(Color.green);
                TxtBan7.requestFocus();
            }
        else if (TxtBan6.getText().equals("")){
            TxtBan6.setBackground(Color.white);
        }
            else{
                TxtBan6.setBackground(Color.red);
                TxtBan6.selectAll();
            }
    }//GEN-LAST:event_TxtBan6KeyReleased

    private void TxtBan7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan7KeyReleased
        if(TxtBan7.getText().equals("R") || TxtBan7.getText().equals("r")){
                TxtBan7.setBackground(Color.green);
                TxtBan8.requestFocus();
            }
        else if (TxtBan7.getText().equals("")){
            TxtBan7.setBackground(Color.white);
        }
            else{
                TxtBan7.setBackground(Color.red);
                TxtBan7.selectAll();
            }
    }//GEN-LAST:event_TxtBan7KeyReleased

    private void TxtBan8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan8KeyReleased
        if(TxtBan8.getText().equals("A") || TxtBan8.getText().equals("a")){
                TxtBan8.setBackground(Color.green);
                TxtBan9.requestFocus();
            }
        else if (TxtBan8.getText().equals("")){
            TxtBan8.setBackground(Color.white);
        }
            else{
                TxtBan8.setBackground(Color.red);
                TxtBan8.selectAll();
            }
    }//GEN-LAST:event_TxtBan8KeyReleased

    private void TxtBan9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan9KeyReleased
        if(TxtBan9.getText().equals("N") || TxtBan9.getText().equals("n")){
                TxtBan9.setBackground(Color.green);
                TxtBan10.requestFocus();
            }
        else if (TxtBan9.getText().equals("")){
            TxtBan9.setBackground(Color.white);
        }
            else{
                TxtBan9.setBackground(Color.red);
                TxtBan9.selectAll();
            }
    }//GEN-LAST:event_TxtBan9KeyReleased

    private void TxtBan10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan10KeyReleased
        if(TxtBan10.getText().equals("T") || TxtBan10.getText().equals("t")){
                TxtBan10.setBackground(Color.green);
                TxtBan11.requestFocus();
            }
        else if (TxtBan10.getText().equals("")){
            TxtBan10.setBackground(Color.white);
        }
            else{
                TxtBan10.setBackground(Color.red);
                TxtBan10.selectAll();
            }
    }//GEN-LAST:event_TxtBan10KeyReleased

    private void TxtBan11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan11KeyReleased
        if(TxtBan11.getText().equals("E") || TxtBan11.getText().equals("e")){
                TxtBan11.setBackground(Color.green);
                TxtBan12.requestFocus();
            }
        else if (TxtBan11.getText().equals("")){
            TxtBan11.setBackground(Color.white);
        }
            else{
                TxtBan11.setBackground(Color.red);
                TxtBan11.selectAll();
            }
    }//GEN-LAST:event_TxtBan11KeyReleased

    private void TxtBan12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBan12KeyReleased
        if(TxtBan12.getText().equals("S") || TxtBan12.getText().equals("s")){
                TxtBan12.setBackground(Color.green);
                
            }
        else if (TxtBan12.getText().equals("")){
            TxtBan12.setBackground(Color.white);
        }
            else{
                TxtBan12.setBackground(Color.red);
                TxtBan12.selectAll();
            }
    }//GEN-LAST:event_TxtBan12KeyReleased

    private void txtSuz1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz1KeyReleased
        if(txtSuz1.getText().equals("S") || txtSuz1.getText().equals("s")){
                txtSuz1.setBackground(Color.green);
                txtSuz2.requestFocus();
            }
        else if (txtSuz1.getText().equals("")){
            txtSuz1.setBackground(Color.white);
        }
            else{
                txtSuz1.setBackground(Color.red);
                txtSuz1.selectAll();
            }
    }//GEN-LAST:event_txtSuz1KeyReleased

    private void txtSuz2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz2KeyReleased
        if(txtSuz2.getText().equals("U") || txtSuz2.getText().equals("u")){
                txtSuz2.setBackground(Color.green);
                txtSuz3.requestFocus();
            }
        else if (txtSuz2.getText().equals("")){
            txtSuz2.setBackground(Color.white);
        }
        
            else{
                txtSuz2.setBackground(Color.red);
                txtSuz2.selectAll();
            }
    }//GEN-LAST:event_txtSuz2KeyReleased

    private void txtSuz3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz3KeyReleased
        if(txtSuz3.getText().equals("Z") || txtSuz3.getText().equals("z")){
                txtSuz3.setBackground(Color.green);
                TxtBan8.requestFocus();
            }
        else if (txtSuz3.getText().equals("")){
            txtSuz3.setBackground(Color.white);
        }
        
            else{
                txtSuz3.setBackground(Color.red);
                txtSuz3.selectAll();
            }
    }//GEN-LAST:event_txtSuz3KeyReleased

    private void txtSuz4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz4KeyReleased
        if(txtSuz4.getText().equals("N") || txtSuz4.getText().equals("n")){
                txtSuz4.setBackground(Color.green);
                txtSuz5.requestFocus();
            }
        else if (txtSuz4.getText().equals("")){
            txtSuz4.setBackground(Color.white);
        }
        
            else{
                txtSuz4.setBackground(Color.red);
                txtSuz4.selectAll();
            }
    }//GEN-LAST:event_txtSuz4KeyReleased

    private void txtSuz5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz5KeyReleased
        if(txtSuz5.getText().equals("A") || txtSuz5.getText().equals("a")){
                txtSuz5.setBackground(Color.green);
                txtSuz6.requestFocus();
            }
        else if (txtSuz5.getText().equals("")){
            txtSuz5.setBackground(Color.white);
        }
        
            else{
                txtSuz5.setBackground(Color.red);
                txtSuz5.selectAll();
            }
    }//GEN-LAST:event_txtSuz5KeyReleased

    private void txtSuz6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz6KeyReleased
        if(txtSuz6.getText().equals(" ") || txtSuz6.getText().equals("-")){
                txtSuz6.setBackground(Color.green);
                txtSuz.requestFocus();
            }
        else if (txtSuz6.getText().equals("")){
            txtSuz6.setBackground(Color.white);
        }
        
            else{
                txtSuz6.setBackground(Color.red);
                txtSuz6.selectAll();
            }
    }//GEN-LAST:event_txtSuz6KeyReleased

    private void txtSuzKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuzKeyReleased
        if(txtSuz.getText().equals("D") || txtSuz.getText().equals("d")){
                txtSuz.setBackground(Color.green);
                txtSuz7.requestFocus();
            }
        else if (txtSuz.getText().equals("")){
            txtSuz.setBackground(Color.white);
        }
        
            else{
                txtSuz.setBackground(Color.red);
                txtSuz.selectAll();
            }
    }//GEN-LAST:event_txtSuzKeyReleased

    private void txtSuz7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz7KeyReleased
        if(txtSuz7.getText().equals("I") || txtSuz7.getText().equals("i")){
                txtSuz7.setBackground(Color.green);
                txtSuz8.requestFocus();
            }
        else if (txtSuz7.getText().equals("")){
            txtSuz7.setBackground(Color.white);
        }
        
            else{
                txtSuz7.setBackground(Color.red);
                txtSuz8.selectAll();
            }
    }//GEN-LAST:event_txtSuz7KeyReleased

    private void txtSuz8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz8KeyReleased
        if(txtSuz8.getText().equals("A") || txtSuz8.getText().equals("a")){
                txtSuz8.setBackground(Color.green);
                txtSuz9.requestFocus();
            }
        else if (txtSuz8.getText().equals("")){
            txtSuz8.setBackground(Color.white);
        }
        
            else{
                txtSuz8.setBackground(Color.red);
                txtSuz8.selectAll();
            }
    }//GEN-LAST:event_txtSuz8KeyReleased

    private void txtSuz9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuz9KeyReleased
        if(txtSuz9.getText().equals("S") || txtSuz9.getText().equals("s")){
                txtSuz9.setBackground(Color.green);
                txtbr4.requestFocus();                
            }
        
        else if (txtSuz9.getText().equals("")){
            txtSuz9.setBackground(Color.white);
        }
        
            else{
                txtSuz9.setBackground(Color.red);
                txtSuz9.selectAll();
            }
    }//GEN-LAST:event_txtSuz9KeyReleased

    private void txtbr1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbr1KeyReleased
        if(txtbr1.getText().equals("B") || txtbr1.getText().equals("b")){
                txtbr1.setBackground(Color.green);
                txtbr2.requestFocus();                
            }
        else if (txtbr1.getText().equals("")){
            txtbr1.setBackground(Color.white);
        }
        
            else{
                txtbr1.setBackground(Color.red);
                txtbr1.selectAll();
            }
    }//GEN-LAST:event_txtbr1KeyReleased

    private void txtbr2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbr2KeyReleased
        if(txtbr2.getText().equals("R") || txtbr2.getText().equals("r")){
                txtbr2.setBackground(Color.green);
                txtbr3.requestFocus();                
            }
          else if (txtbr2.getText().equals("")){
            txtbr2.setBackground(Color.white);
        }
            else{
                txtbr2.setBackground(Color.red);
                txtbr2.selectAll();
            }
    }//GEN-LAST:event_txtbr2KeyReleased

    private void txtbr3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbr3KeyReleased
        if(txtbr3.getText().equals("A") || txtbr3.getText().equals("A")){
                txtbr3.setBackground(Color.green);
                txtSuz9.requestFocus();                
            }
          else if (txtbr3.getText().equals("")){
            txtbr3.setBackground(Color.white);
        }
            else{
                txtbr3.setBackground(Color.red);
                txtbr3.selectAll();
            }
    }//GEN-LAST:event_txtbr3KeyReleased

    private void txtbr4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbr4KeyReleased
        if(txtbr4.getText().equals("I") || txtbr4.getText().equals("i")){
                txtbr4.setBackground(Color.green);
                txtbr5.requestFocus();                
            }
          else if (txtbr4.getText().equals("")){
            txtbr4.setBackground(Color.white);
        }
            else{
                txtbr4.setBackground(Color.red);
                txtbr4.selectAll();
            }
    }//GEN-LAST:event_txtbr4KeyReleased

    private void txtbr5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbr5KeyReleased
        if(txtbr5.getText().equals("l") || txtbr5.getText().equals("L")){
                txtbr5.setBackground(Color.green);
                                
            }
          else if (txtbr5.getText().equals("")){
            txtbr5.setBackground(Color.white);
        }
        
        
            else{
                txtbr5.setBackground(Color.red);
                txtbr5.selectAll();
            }
    }//GEN-LAST:event_txtbr5KeyReleased

    private void txtBorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBorKeyReleased
        if(txtBor.getText().equals("B") || txtBor.getText().equals("b")){
                txtBor.setBackground(Color.green);
                txtBor1.requestFocus();                
            }
          else if (txtBor.getText().equals("")){
            txtBor.setBackground(Color.white);
        }
            else{
                txtBor.setBackground(Color.red);
                txtBor.selectAll();
            }
    }//GEN-LAST:event_txtBorKeyReleased

    private void txtBor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor1KeyReleased
        if(txtBor1.getText().equals("O") || txtBor1.getText().equals("o")){
                txtBor1.setBackground(Color.green);
                txtbr2.requestFocus();                
            }
         else if (txtBor1.getText().equals("")){
            txtBor1.setBackground(Color.white);
        }
            else{
                txtBor1.setBackground(Color.red);
                txtBor1.selectAll();
            }
    }//GEN-LAST:event_txtBor1KeyReleased

    private void txtBor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor2KeyReleased
        if(txtBor2.getText().equals("B") || txtBor2.getText().equals("b")){
                txtBor2.setBackground(Color.green);
                txtBor3.requestFocus();                
            }
         else if (txtBor2.getText().equals("")){
            txtBor2.setBackground(Color.white);
        }
            else{
                txtBor2.setBackground(Color.red);
                txtBor2.selectAll();
            }
    }//GEN-LAST:event_txtBor2KeyReleased

    private void txtBor3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor3KeyReleased
        if(txtBor3.getText().equals("A") || txtBor3.getText().equals("a")){
                txtBor3.setBackground(Color.green);
                txtBor4.requestFocus();                
            }
         else if (txtBor3.getText().equals("")){
            txtBor3.setBackground(Color.white);
        }
            else{
                txtBor3.setBackground(Color.red);
                txtBor3.selectAll();
            }
    }//GEN-LAST:event_txtBor3KeyReleased

    private void txtBor4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor4KeyReleased
        if(txtBor4.getText().equals(" ") || txtBor4.getText().equals("-")){
                txtBor4.setBackground(Color.green);
                txtBor5.requestFocus();                
            }
         else if (txtBor4.getText().equals("")){
            txtBor4.setBackground(Color.white);
        }
            else{
                txtBor4.setBackground(Color.red);
                txtBor4.selectAll();
            }
    }//GEN-LAST:event_txtBor4KeyReleased

    private void txtBor5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor5KeyReleased
        if(txtBor5.getText().equals("G") || txtBor5.getText().equals("g")){
                txtBor5.setBackground(Color.green);
                txtBor6.requestFocus();                
            }
            else{
                txtBor5.setBackground(Color.red);
                txtBor5.selectAll();
            }
    }//GEN-LAST:event_txtBor5KeyReleased

    private void txtBor6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor6KeyReleased
        if(txtBor6.getText().equals("A") || txtBor6.getText().equals("a")){
                txtBor6.setBackground(Color.green);
                txtBor7.requestFocus();                
            }
            else{
                txtBor6.setBackground(Color.red);
                txtBor6.selectAll();
        }
    }//GEN-LAST:event_txtBor6KeyReleased

    private void txtBor7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor7KeyReleased
        if(txtBor7.getText().equals("T") || txtBor7.getText().equals("t")){
                txtBor7.setBackground(Color.green);
                txtBor8.requestFocus();                
            }
            else{
                txtBor7.setBackground(Color.red);
                txtBor7.selectAll();
        }
    }//GEN-LAST:event_txtBor7KeyReleased

    private void txtBor8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBor8KeyReleased
        if(txtBor8.getText().equals("O") || txtBor8.getText().equals("o")){
                txtBor8.setBackground(Color.green);
                                
            }
            else{
                txtBor8.setBackground(Color.red);
                txtBor8.selectAll();
        }
    }//GEN-LAST:event_txtBor8KeyReleased

    private void txtFerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFerKeyReleased
       if(txtFer.getText().equals("F") || txtFer.getText().equals("f")){
                txtFer.setBackground(Color.green);
                txtFer1.requestFocus();                
            }
            else{
                txtFer.setBackground(Color.red);
                txtFer.selectAll();
        }
    }//GEN-LAST:event_txtFerKeyReleased

    private void txtFer1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFer1KeyReleased
        if(txtFer1.getText().equals("E") || txtFer1.getText().equals("e")){
                txtFer1.setBackground(Color.green);
                txtFer2.requestFocus();                
            }
            else{
                txtFer1.setBackground(Color.red);
                txtFer1.selectAll();
        }
    }//GEN-LAST:event_txtFer1KeyReleased

    private void txtFer2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFer2KeyReleased
        if(txtFer2.getText().equals("R") || txtFer2.getText().equals("r")){
                txtFer2.setBackground(Color.green);
                txtFer3.requestFocus();                
            }
            else{
                txtFer2.setBackground(Color.red);
                txtFer2.selectAll();
        }
    }//GEN-LAST:event_txtFer2KeyReleased

    private void txtFer3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFer3KeyReleased
        if(txtFer3.getText().equals("N") || txtFer3.getText().equals("n")){
                txtFer3.setBackground(Color.green);
                txtFer4.requestFocus();                
            }
            else{
                txtFer3.setBackground(Color.red);
                txtFer3.selectAll();
        }
    }//GEN-LAST:event_txtFer3KeyReleased

    private void txtFer4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFer4KeyReleased
        if(txtFer4.getText().equals("Ã") || txtFer4.getText().equals("ã")){
                txtFer4.setBackground(Color.green);
                txtBor8.requestFocus();                
            }
            else{
                txtFer4.setBackground(Color.red);
                txtFer4.selectAll();
        }
    }//GEN-LAST:event_txtFer4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hist_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hist_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hist_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hist_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hist_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBan1;
    private javax.swing.JTextField TxtBan10;
    private javax.swing.JTextField TxtBan11;
    private javax.swing.JTextField TxtBan12;
    private javax.swing.JTextField TxtBan13;
    private javax.swing.JTextField TxtBan3;
    private javax.swing.JTextField TxtBan4;
    private javax.swing.JTextField TxtBan5;
    private javax.swing.JTextField TxtBan6;
    private javax.swing.JTextField TxtBan7;
    private javax.swing.JTextField TxtBan8;
    private javax.swing.JTextField TxtBan9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBor;
    private javax.swing.JTextField txtBor1;
    private javax.swing.JTextField txtBor2;
    private javax.swing.JTextField txtBor3;
    private javax.swing.JTextField txtBor4;
    private javax.swing.JTextField txtBor5;
    private javax.swing.JTextField txtBor6;
    private javax.swing.JTextField txtBor7;
    private javax.swing.JTextField txtBor8;
    private javax.swing.JTextField txtFer;
    private javax.swing.JTextField txtFer1;
    private javax.swing.JTextField txtFer2;
    private javax.swing.JTextField txtFer3;
    private javax.swing.JTextField txtFer4;
    private javax.swing.JTextField txtSuz;
    private javax.swing.JTextField txtSuz1;
    private javax.swing.JTextField txtSuz2;
    private javax.swing.JTextField txtSuz3;
    private javax.swing.JTextField txtSuz4;
    private javax.swing.JTextField txtSuz5;
    private javax.swing.JTextField txtSuz6;
    private javax.swing.JTextField txtSuz7;
    private javax.swing.JTextField txtSuz8;
    private javax.swing.JTextField txtSuz9;
    private javax.swing.JTextField txtbr1;
    private javax.swing.JTextField txtbr2;
    private javax.swing.JTextField txtbr3;
    private javax.swing.JTextField txtbr4;
    private javax.swing.JTextField txtbr5;
    // End of variables declaration//GEN-END:variables
}
