/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author sanilso
 */
public class Port_1 extends javax.swing.JFrame {
    boolean resp1,resp2,resp3,resp4,resp5,resp6;
    /**
     * Creates new form Port_1
     */
    public Port_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Palavra1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Palavra2 = new javax.swing.JLabel();
        Palavra3 = new javax.swing.JLabel();
        Palavra4 = new javax.swing.JLabel();
        Palavra5 = new javax.swing.JLabel();
        Palavra6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtResp1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResp2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtResp3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtResp4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtResp5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtResp6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Palavra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra1.setText("heróis");
        Palavra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra1MouseDragged(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Palavra2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra2.setText("Bandeirantes");
        Palavra2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra2MouseDragged(evt);
            }
        });

        Palavra3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra3.setText("Dias");
        Palavra3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra3MouseDragged(evt);
            }
        });

        Palavra4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra4.setText("Ignorados");
        Palavra4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra4MouseDragged(evt);
            }
        });

        Palavra5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra5.setText("Santana");
        Palavra5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra5MouseDragged(evt);
            }
        });

        Palavra6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Palavra6.setText("Engrandeçam");
        Palavra6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Palavra6MouseDragged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Santana de Parnaíba");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Berço de");

        txtResp1.setEditable(false);
        txtResp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp1MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("consagrados");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cidade dos Bandeirantes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Deste solo muito amado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Com orgulho festejamos");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("O dia dos");

        txtResp2.setEditable(false);
        txtResp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp2MouseEntered(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Salve! Anhanguera, Borba Gato,");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Fernão e Suzana ");

        txtResp3.setEditable(false);
        txtResp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp3MouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bravos heróis do passado");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Daqui partiram as bandeiras");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Por rincões ");

        txtResp4.setEditable(false);
        txtResp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp4MouseEntered(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Levando no peito a cruz");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Nos lábios o nome amado\t");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("De");

        txtResp5.setEditable(false);
        txtResp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp5MouseEntered(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("de Parnaíba");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Essa terra alvissareira");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Viva! Esses homens destemidos");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Vivam todos que ");

        txtResp6.setEditable(false);
        txtResp6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtResp6MouseEntered(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Nossa terra brasileira!");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Próximo Nível");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtResp1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResp2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtResp3))
                                .addComponent(jLabel8))
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtResp4))
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtResp5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16))
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtResp6)))
                            .addComponent(jLabel20))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Palavra5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Palavra3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Palavra1)
                        .addGap(110, 110, 110)
                        .addComponent(Palavra4)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Palavra6)
                        .addGap(76, 76, 76)
                        .addComponent(Palavra2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Palavra2)
                        .addComponent(Palavra6)
                        .addComponent(Palavra5))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Palavra1)
                    .addComponent(Palavra4)
                    .addComponent(Palavra3))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtResp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtResp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtResp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtResp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtResp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtResp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Palavra1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra1MouseDragged
        Palavra1.setLocation(Palavra1.getX() + evt.getX(), Palavra1.getY() + evt.getY());
        resp1 = true;
        resp2 = false;
        resp3 = false;
        resp4 = false;
        resp5 = false;
        resp6 = false;    
    }//GEN-LAST:event_Palavra1MouseDragged

    private void Palavra2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra2MouseDragged
        Palavra2.setLocation(Palavra2.getX() + evt.getX(), Palavra2.getY() + evt.getY());
        resp1 = false;
        resp2 = true;
        resp3 = false;
        resp4 = false;
        resp5 = false;
        resp6 = false;
    }//GEN-LAST:event_Palavra2MouseDragged

    private void Palavra3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra3MouseDragged
        Palavra3.setLocation(Palavra3.getX() + evt.getX(), Palavra3.getY() + evt.getY());
        resp1 = false;
        resp2 = false;
        resp3 = true;
        resp4 = false;
        resp5 = false;
        resp6 = false;
    }//GEN-LAST:event_Palavra3MouseDragged

    private void Palavra4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra4MouseDragged
        Palavra4.setLocation(Palavra4.getX() + evt.getX(), Palavra4.getY() + evt.getY());
        resp1 = false;
        resp2 = false;
        resp3 = false;
        resp4 = true;
        resp5 = false;
        resp6 = false;
    }//GEN-LAST:event_Palavra4MouseDragged

    private void Palavra5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra5MouseDragged
        Palavra5.setLocation(Palavra5.getX() + evt.getX(), Palavra5.getY() + evt.getY());
        resp1 = false;
        resp2 = false;
        resp3 = false;
        resp4 = false;
        resp5 = true;
        resp6 = false;
    }//GEN-LAST:event_Palavra5MouseDragged

    private void Palavra6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Palavra6MouseDragged
        Palavra6.setLocation(Palavra6.getX() + evt.getX(), Palavra6.getY() + evt.getY());
        resp1 = false;
        resp2 = false;
        resp3 = false;
        resp4 = false;
        resp5 = false;
        resp6 = true;
    }//GEN-LAST:event_Palavra6MouseDragged

    private void txtResp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp1MouseEntered
       
        if(resp1){
            Palavra1.setVisible(false);
            txtResp1.setText("hérois");
            txtResp1.setBackground(Color.green);
            resp1= false;
        }
        else if (resp2) {
            Palavra2.setBounds(387, 18, 78, 17);
            resp2 = false;
        }
        else if (resp3) {
            Palavra3.setBounds(86, 52, 25, 17);
            resp3 = false;
        }
        else if (resp4){
            Palavra4.setBounds(393, 52, 62, 17);
            resp4 = false;
        }
        else if (resp5){
            Palavra5.setBounds(78, 18, 50, 17);
            resp5 = false;
        }
        else if (resp6){
            Palavra6.setBounds(230, 18, 86, 16);
            resp6 = false;
        }        
    }//GEN-LAST:event_txtResp1MouseEntered

    private void txtResp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp2MouseEntered
        if(resp2){
            Palavra2.setVisible(false);
            txtResp2.setText("Bandeirantes");
            txtResp2.setBackground(Color.green);
            resp2= false;
        }
        else if (resp1) {
            Palavra1.setBounds(245, 52, 36, 17);
            resp1 = false;
        }
        else if (resp3) {
            Palavra3.setBounds(86, 52, 25, 17);
            resp3 = false;
        }
        else if (resp4){
            Palavra4.setBounds(393, 52, 62, 17);
            resp4 = false;
        }
        else if (resp5){
            Palavra5.setBounds(78, 18, 50, 17);
            resp5 = false;
        }
        else if (resp6){
            Palavra6.setBounds(230, 18, 86, 16);
            resp6 = false;
        }
    }//GEN-LAST:event_txtResp2MouseEntered

    private void txtResp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp3MouseEntered
        
        if(resp3){
            Palavra3.setVisible(false);
            txtResp3.setText("Dias");
            txtResp3.setBackground(Color.green);
            resp3= false;
        }
        else if (resp1) {
            Palavra1.setBounds(245, 52, 36, 17);
            resp1 = false;
        }
        else if (resp2) {
            Palavra2.setBounds(387, 18, 78, 17);
            resp2 = false;
        }
        else if (resp4){
            Palavra4.setBounds(393, 52, 62, 17);
            resp4 = false;
        }
        else if (resp5){
            Palavra5.setBounds(78, 18, 50, 17);
            resp5 = false;
        }
        else if (resp6){
            Palavra6.setBounds(230, 18, 86, 16);
            resp6 = false;
        }
    }//GEN-LAST:event_txtResp3MouseEntered

    private void txtResp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp4MouseEntered
        if(resp4){
            Palavra4.setVisible(false);
            txtResp4.setText("ignorados");
            txtResp4.setBackground(Color.green);
            resp4= false;
        }
        else if (resp1) {
            Palavra1.setBounds(245, 52, 36, 17);
            resp1 = false;
        }
        else if (resp2) {
            Palavra2.setBounds(387, 18, 78, 17);
            resp2 = false;
        }
        else if (resp3) {
            Palavra3.setBounds(86, 52, 25, 17);
            resp3 = false;
        }
        else if (resp5){
            Palavra5.setBounds(78, 18, 50, 17);
            resp5 = false;
        }
        else if (resp6){
            Palavra6.setBounds(230, 18, 86, 16);
            resp6 = false;
        }
    }//GEN-LAST:event_txtResp4MouseEntered

    private void txtResp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp5MouseEntered
        if(resp5){
            Palavra5.setVisible(false);
            txtResp5.setText("Santana");
            txtResp5.setBackground(Color.green);
            resp5= false;
        }
        else if (resp1) {
            Palavra1.setBounds(245, 52, 36, 17);
            resp1 = false;
        }
        else if (resp2) {
            Palavra2.setBounds(387, 18, 78, 17);
            resp2 = false;
        }
        else if (resp3) {
            Palavra3.setBounds(86, 52, 25, 17);
            resp3 = false;
        }
        else if (resp4){
            Palavra4.setBounds(393, 52, 62, 17);
            resp4 = false;
        }
        else if (resp6){
            Palavra6.setBounds(230, 18, 86, 16);
            resp6 = false;
        }
    }//GEN-LAST:event_txtResp5MouseEntered

    private void txtResp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResp6MouseEntered
        if(resp6){
            Palavra6.setVisible(false);
            txtResp6.setText("engrandeçam");
            txtResp6.setBackground(Color.green);
            resp6= false;
        }
        else if (resp1) {
            Palavra1.setBounds(245, 52, 36, 17);
            resp1 = false;
        }
        else if (resp2) {
            Palavra2.setBounds(387, 18, 78, 17);
            resp2 = false;
        }
        else if (resp3) {
            Palavra3.setBounds(86, 52, 25, 17);
            resp3 = false;
        }
        else if (resp4){
            Palavra4.setBounds(393, 52, 62, 17);
            resp4 = false;
        }
        else if (resp5){
            Palavra5.setBounds(78, 18, 50, 17);
            resp5 = false;
        }
    }//GEN-LAST:event_txtResp6MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null ,"Arraste as palavras para a caixinha que você acha que está correta!!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Portugues mec = new Portugues();
        mec.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Port_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Port_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Port_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Port_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Port_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Palavra1;
    private javax.swing.JLabel Palavra2;
    private javax.swing.JLabel Palavra3;
    private javax.swing.JLabel Palavra4;
    private javax.swing.JLabel Palavra5;
    private javax.swing.JLabel Palavra6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtResp1;
    private javax.swing.JTextField txtResp2;
    private javax.swing.JTextField txtResp3;
    private javax.swing.JTextField txtResp4;
    private javax.swing.JTextField txtResp5;
    private javax.swing.JTextField txtResp6;
    // End of variables declaration//GEN-END:variables
}
